package com.escod.compiler.cup;
import java_cup.runtime.Symbol;

parser code
{:
    private Symbol s;

    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
}
:};

terminal
Espacio, If, Parentesis_abierto, Parentesis_cerrado, P_coma, Igual, Numero, Identificador, Else,ERROR;

nonterminal  SENTENCIA, SENTENCIA_BOOLEANA, DECLARACION, IF, IF_ELSE ;

start with SENTENCIA;

SENTENCIA ::=
//    IF                  |
//    SENTENCIA IF        |
    SENTENCIA IF_ELSE             |
//    SENTENCIA IF_ELSE   |
//    SENTENCIA DECLARACION
;

//IF ::= If Parentesis_abierto SENTENCIA_BOOLEANA Parentesis_cerrado SENTENCIA ;
IF_ELSE ::= If
 Parentesis_abierto SENTENCIA_BOOLEANA Parentesis_cerrado
  Espacio DECLARACION Espacio Else Espacio DECLARACION;
SENTENCIA_BOOLEANA ::= Identificador Igual Numero;
DECLARACION ::= Identificador  Igual Numero P_coma;
