package com.escod.compiler.cup;
import java_cup.runtime.Symbol;

parser code
{:
    private Symbol s;

    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
}
:};

terminal  Op_booleano, Parentesis_a, Parentesis_c,
    Numero, AND, OR, NOT, ERROR;

non terminal INICIO, EXPRESION;

start with INICIO;

INICIO ::=
        EXPRESION:e                                     {: System.out.println(e);:}
    |   Parentesis_a EXPRESION:e  Parentesis_c          {: System.out.println(e);:}
    |   EXPRESION Parentesis_a EXPRESION:e  Parentesis_c          {: System.out.println(e);:}
;
EXPRESION ::=
        Op_booleano:n1 AND Op_booleano:n2               {: RESULT= "n1 && n2" :}
    |   Op_booleano:n1 OR Op_booleano:n2                {: RESULT= "n1 || n2" :}
    |   NOT:n                                    {: RESULT= "!n":}
;
