package com.escod.compiler.cup;
import java_cup.runtime.Symbol;

parser code
{:
    private Symbol s;

    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
}
:};

terminal
    Parentesis_abierto, Parentesis_cerrado, Numero, AND, OR, NOT;

non terminal INICIO, SENTENCIA, SENTENCIA_AND, SENTENCIA_OR, SENTENCIA_NOT;

start with INICIO;

INICIO ::=
    Parentesis_abierto SENTENCIA Parentesis_cerrado|
    SENTENCIA
;
SENTENCIA ::=
    SENTENCIA_AND|
    SENTENCIA_OR |
    SENTENCIA_NOT
;

SENTENCIA_AND ::=
    Numero AND Numero
;
SENTENCIA_OR ::=
    Numero OR Numero
;
SENTENCIA_NOT ::=
    Numero NOT Numero
;
