
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.escod.compiler.cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int Else = 10;
  public static final int If = 3;
  public static final int Parentesis_abierto = 4;
  public static final int ERROR = 11;
  public static final int EOF = 0;
  public static final int P_coma = 6;
  public static final int Identificador = 9;
  public static final int Parentesis_cerrado = 5;
  public static final int error = 1;
  public static final int Igual = 7;
  public static final int Numero = 8;
  public static final int Espacio = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Espacio",
  "If",
  "Parentesis_abierto",
  "Parentesis_cerrado",
  "P_coma",
  "Igual",
  "Numero",
  "Identificador",
  "Else",
  "ERROR"
  };
}

