
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.escod.compiler.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 5;
  public static final int Parentesis_abierto = 2;
  public static final int EOF = 0;
  public static final int Parentesis_cerrado = 3;
  public static final int error = 1;
  public static final int NOT = 7;
  public static final int Numero = 4;
  public static final int OR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Parentesis_abierto",
  "Parentesis_cerrado",
  "Numero",
  "AND",
  "OR",
  "NOT"
  };
}

